### ISSUE TITLE
How to update subTitle

### ISSUE THREAD

**Issue by fairytale110** [HamidrezaAmz/MagicalNotifier#1]
if i have shown an Notifier, now i need to update the value of subTitle ,which API should i use?

**Comment by HamidrezaAmz** [comment]
**If you want to update title or subTitle of a notifiaction you should pass an id for your notification and use same `MagicalNotifier` object, check out this example**

```
int notificationId = 8585;

MagicalNotifier magicalNotifier = new MagicalNotifier.Builder(this)
                .setNotificationId(notificationId)
                .setTitle(NOTIFICATION_TITLE)
                .setSubTitle(NOTIFICATION_SUB_TITLE)
                .show();
```

**You can update notification**
```magicalNotifier.getBuilder().notifyTitle(notificationId, "Title updated");```

**Do not forget to update your lib to last version**
